# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqpFt5ZRFp_fzDXQ0PGyDcAJTkXJWf9U
"""

import pandas as pd
teacher=pd.DataFrame({
    "FISH":["Qadamova Z.E", "Arabboev A.A", "Burxonova M.M", "Jalilov M.L", "Xalilov D.A"    ],
    "Fan nomi":["suniy intellekt", "kiberxavfsizlik asoslari", "kompyuterni tashkil etish", "kompyuterni tashkil etish", "suniy intellekt"  ],
    "Mashg'ulot turi":["amaliy", "amaliy", "amaliy", "maruza", "maruza"   ],
    "Dars o'tish mahorati":["yaxshi", "yaxshi", "yaxshi", "yaxshi", "yaxshi" ]
})
print(teacher)

teacher.to_excel("teacher.xlsx")